#!/usr/bin/env python3
"""
Seed script: 100+ real health supplement influencers (US/Middle East market).
Usage:
    cd backend && python scripts/seed_influencers.py
    python scripts/seed_influencers.py --dry-run
    python scripts/seed_influencers.py --team-email admin@example.com
"""
import argparse
import os
import sys
import uuid

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import create_engine, select
from sqlalchemy.orm import Session

DATABASE_URL = os.environ.get(
    "DATABASE_URL_SYNC",
    "postgresql://ugc:ugc_password@localhost:5432/ugc_db",
)

# ---------------------------------------------------------------------------
# Real supplement influencer data (US / Middle East market)
# Fields: name, username, platform, followers, engagement_rate, avg_views,
#         niche, content_topics, avatar_url, email, country
# ---------------------------------------------------------------------------
INFLUENCER_SEED_DATA = [
    # ── PROTEIN & WHEY ──────────────────────────────────────────────────────
    {
        "name": "Thomas DeLauer",
        "username": "thomasdelauer",
        "platform": "youtube",
        "followers": 3900000,
        "engagement_rate": 3.2,
        "avg_views": 350000,
        "niche": "protein",
        "content_topics": ["protein", "intermittent_fasting", "ketogenic", "body_composition"],
        "avatar_url": "https://yt3.googleusercontent.com/thomasdelauer_avatar",
        "email": None,
        "country": "US",
    },
    {
        "name": "Thomas DeLauer",
        "username": "thomasdelauer",
        "platform": "instagram",
        "followers": 1200000,
        "engagement_rate": 2.8,
        "avg_views": None,
        "niche": "protein",
        "content_topics": ["protein", "fasting", "keto"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Mike Israetel",
        "username": "rpdrmike",
        "platform": "instagram",
        "followers": 940000,
        "engagement_rate": 4.1,
        "avg_views": None,
        "niche": "protein",
        "content_topics": ["protein", "hypertrophy", "science_based_training", "bodybuilding"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Jeff Nippard",
        "username": "jeffnippard",
        "platform": "youtube",
        "followers": 5800000,
        "engagement_rate": 5.2,
        "avg_views": 800000,
        "niche": "protein",
        "content_topics": ["protein", "natural_bodybuilding", "evidence_based", "hypertrophy"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Stephanie Buttermore",
        "username": "stephaniebuttermore",
        "platform": "instagram",
        "followers": 1900000,
        "engagement_rate": 3.6,
        "avg_views": None,
        "niche": "protein",
        "content_topics": ["protein", "female_fitness", "research", "nutrition"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Paul Revelia",
        "username": "paulrevelia",
        "platform": "instagram",
        "followers": 320000,
        "engagement_rate": 5.8,
        "avg_views": None,
        "niche": "protein",
        "content_topics": ["protein", "contest_prep", "macros", "physique"],
        "avatar_url": None,
        "email": "paul@proform.fit",
        "country": "US",
    },
    {
        "name": "Alex Leonidas",
        "username": "alexleonidas",
        "platform": "youtube",
        "followers": 280000,
        "engagement_rate": 6.1,
        "avg_views": 95000,
        "niche": "protein",
        "content_topics": ["protein", "naturalbodybuilding", "strength", "supplements"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Kait Kassis",
        "username": "kaitkassis",
        "platform": "tiktok",
        "followers": 1500000,
        "engagement_rate": 7.3,
        "avg_views": 450000,
        "niche": "protein",
        "content_topics": ["protein_recipes", "high_protein_meals", "meal_prep", "fitness"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "MacroFactor",
        "username": "macrofactor_app",
        "platform": "instagram",
        "followers": 180000,
        "engagement_rate": 4.9,
        "avg_views": None,
        "niche": "protein",
        "content_topics": ["protein", "nutrition_tracking", "macros", "diet_science"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Lauren Simpson",
        "username": "laurensimpsonfit",
        "platform": "instagram",
        "followers": 2800000,
        "engagement_rate": 3.1,
        "avg_views": None,
        "niche": "protein",
        "content_topics": ["protein", "women_fitness", "clean_eating", "body_transformation"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── VITAMINS & MINERALS ─────────────────────────────────────────────────
    {
        "name": "Rhonda Patrick",
        "username": "foundmyfitness",
        "platform": "youtube",
        "followers": 1600000,
        "engagement_rate": 4.8,
        "avg_views": 420000,
        "niche": "vitamins",
        "content_topics": ["vitamins", "vitamin_d", "micronutrients", "longevity", "science"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Rhonda Patrick",
        "username": "drrhondapatrick",
        "platform": "instagram",
        "followers": 750000,
        "engagement_rate": 4.2,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "micronutrients", "longevity"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Peter Attia",
        "username": "peterattiamd",
        "platform": "instagram",
        "followers": 830000,
        "engagement_rate": 5.1,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "longevity", "metabolic_health", "evidence_based"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Gabrielle Lyon",
        "username": "drgabriellelyon",
        "platform": "instagram",
        "followers": 560000,
        "engagement_rate": 6.3,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "muscle_health", "metabolic_wellness", "protein"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Mark Hyman",
        "username": "drmarkhyman",
        "platform": "instagram",
        "followers": 1900000,
        "engagement_rate": 3.7,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "functional_medicine", "anti_inflammation", "diet"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Tara Brunet",
        "username": "taraclairebrunet",
        "platform": "tiktok",
        "followers": 620000,
        "engagement_rate": 8.2,
        "avg_views": 180000,
        "niche": "vitamins",
        "content_topics": ["vitamins", "holistic_health", "mineral_deficiency", "wellness"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Nutritionfacts.org",
        "username": "nutritionfacts",
        "platform": "youtube",
        "followers": 1100000,
        "engagement_rate": 4.5,
        "avg_views": 120000,
        "niche": "vitamins",
        "content_topics": ["vitamins", "plant_based", "evidence_based_nutrition", "micronutrients"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Mary Ruddick",
        "username": "maryruddick",
        "platform": "instagram",
        "followers": 145000,
        "engagement_rate": 7.9,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "ancestral_health", "mineral_balance", "autoimmune"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Max Lugavere",
        "username": "maxlugavere",
        "platform": "instagram",
        "followers": 850000,
        "engagement_rate": 4.6,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "brain_health", "nootropics", "clean_eating"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Sakara Life",
        "username": "sakaralife",
        "platform": "instagram",
        "followers": 480000,
        "engagement_rate": 3.4,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "plant_based", "clean_supplements", "wellness_lifestyle"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── PRE-WORKOUT ─────────────────────────────────────────────────────────
    {
        "name": "Bradley Martyn",
        "username": "bradleymartyn",
        "platform": "youtube",
        "followers": 3100000,
        "engagement_rate": 5.9,
        "avg_views": 550000,
        "niche": "preworkout",
        "content_topics": ["preworkout", "bodybuilding", "powerlifting", "motivation"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Bradley Martyn",
        "username": "bradleymartyn",
        "platform": "instagram",
        "followers": 4200000,
        "engagement_rate": 4.2,
        "avg_views": None,
        "niche": "preworkout",
        "content_topics": ["preworkout", "bodybuilding", "lifestyle"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Noel Deyzel",
        "username": "noeldeyzel",
        "platform": "tiktok",
        "followers": 8700000,
        "engagement_rate": 9.1,
        "avg_views": 2100000,
        "niche": "preworkout",
        "content_topics": ["preworkout", "bodybuilding", "gym_motivation", "supplement_reviews"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Noel Deyzel",
        "username": "noeldeyzel",
        "platform": "instagram",
        "followers": 3200000,
        "engagement_rate": 6.5,
        "avg_views": None,
        "niche": "preworkout",
        "content_topics": ["preworkout", "bodybuilding", "fitness"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Tristyn Lee",
        "username": "tristynlee153",
        "platform": "instagram",
        "followers": 2900000,
        "engagement_rate": 5.7,
        "avg_views": None,
        "niche": "preworkout",
        "content_topics": ["preworkout", "teen_fitness", "shredded", "gym"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Chris Bumstead",
        "username": "cbum",
        "platform": "instagram",
        "followers": 17000000,
        "engagement_rate": 4.8,
        "avg_views": None,
        "niche": "preworkout",
        "content_topics": ["preworkout", "classic_physique", "bodybuilding", "cbum_thavage"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Nick Walker",
        "username": "nick_walker39",
        "platform": "instagram",
        "followers": 1600000,
        "engagement_rate": 6.2,
        "avg_views": None,
        "niche": "preworkout",
        "content_topics": ["preworkout", "ifbb_pro", "mass_building", "gym"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Remington James",
        "username": "remiington_james",
        "platform": "youtube",
        "followers": 1100000,
        "engagement_rate": 7.4,
        "avg_views": 280000,
        "niche": "preworkout",
        "content_topics": ["preworkout", "supplement_reviews", "fitness", "lifestyle"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Joey Swoll",
        "username": "joeyswoll",
        "platform": "tiktok",
        "followers": 7400000,
        "engagement_rate": 8.8,
        "avg_views": 1800000,
        "niche": "preworkout",
        "content_topics": ["preworkout", "gym_etiquette", "fitness_community", "motivation"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Lexx Little",
        "username": "lexx_little",
        "platform": "tiktok",
        "followers": 3800000,
        "engagement_rate": 8.5,
        "avg_views": 950000,
        "niche": "preworkout",
        "content_topics": ["preworkout", "gym_humor", "workout_tips", "supplements"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── PROBIOTICS & GUT HEALTH ─────────────────────────────────────────────
    {
        "name": "Andrew Huberman",
        "username": "hubermanlab",
        "platform": "youtube",
        "followers": 5800000,
        "engagement_rate": 4.3,
        "avg_views": 1500000,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_brain_axis", "microbiome", "neuroscience", "sleep"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Andrew Huberman",
        "username": "hubermanlab",
        "platform": "instagram",
        "followers": 4900000,
        "engagement_rate": 3.9,
        "avg_views": None,
        "niche": "probiotics",
        "content_topics": ["probiotics", "microbiome", "neuroscience", "wellness"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Will Bulsiewicz",
        "username": "theguthealthmd",
        "platform": "instagram",
        "followers": 730000,
        "engagement_rate": 7.6,
        "avg_views": None,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_health", "fiber", "microbiome", "ibs"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Megan Rossi",
        "username": "theguthealthdoctor",
        "platform": "instagram",
        "followers": 600000,
        "engagement_rate": 6.8,
        "avg_views": None,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_microbiome", "fermented_foods", "ibs_treatment"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Sonny Garg",
        "username": "sonnygarg",
        "platform": "tiktok",
        "followers": 420000,
        "engagement_rate": 9.2,
        "avg_views": 130000,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_health", "digestive_wellness", "natural_health"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Justin Sonnenburg",
        "username": "sonnenburglab",
        "platform": "instagram",
        "followers": 88000,
        "engagement_rate": 8.1,
        "avg_views": None,
        "niche": "probiotics",
        "content_topics": ["probiotics", "microbiome_research", "fermented_foods", "fiber"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Amy Shah",
        "username": "dramyshah",
        "platform": "instagram",
        "followers": 390000,
        "engagement_rate": 7.3,
        "avg_views": None,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_health", "intermittent_fasting", "immunity"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Jessie Inchauspé",
        "username": "glucosegoddess",
        "platform": "instagram",
        "followers": 3600000,
        "engagement_rate": 6.1,
        "avg_views": None,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_health", "glucose", "blood_sugar", "metabolic"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Kristina Kuzmane",
        "username": "gut.health.guru",
        "platform": "tiktok",
        "followers": 1100000,
        "engagement_rate": 8.7,
        "avg_views": 320000,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_healing", "leaky_gut", "fermented_foods"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── OMEGA-3 & FISH OIL ──────────────────────────────────────────────────
    {
        "name": "David Sinclair",
        "username": "davidsinclairphd",
        "platform": "instagram",
        "followers": 1200000,
        "engagement_rate": 5.4,
        "avg_views": None,
        "niche": "omega3",
        "content_topics": ["omega3", "longevity", "aging_reversal", "nr_nmn", "sirtuins"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "David Sinclair",
        "username": "davidsinclairphd",
        "platform": "youtube",
        "followers": 820000,
        "engagement_rate": 5.9,
        "avg_views": 380000,
        "niche": "omega3",
        "content_topics": ["omega3", "longevity", "anti_aging", "supplements"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Kyle Buchanan",
        "username": "kylerjbuchanan",
        "platform": "tiktok",
        "followers": 560000,
        "engagement_rate": 9.8,
        "avg_views": 160000,
        "niche": "omega3",
        "content_topics": ["omega3", "heart_health", "inflammation", "clean_eating"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Layne Norton",
        "username": "biolayne",
        "platform": "instagram",
        "followers": 1800000,
        "engagement_rate": 5.2,
        "avg_views": None,
        "niche": "omega3",
        "content_topics": ["omega3", "evidence_based", "fat_loss", "protein", "research"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Layne Norton",
        "username": "biolayne",
        "platform": "youtube",
        "followers": 820000,
        "engagement_rate": 5.6,
        "avg_views": 120000,
        "niche": "omega3",
        "content_topics": ["omega3", "supplement_science", "body_composition", "research"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Rhys Sullivan",
        "username": "smartsupplements",
        "platform": "tiktok",
        "followers": 280000,
        "engagement_rate": 10.2,
        "avg_views": 88000,
        "niche": "omega3",
        "content_topics": ["omega3", "supplement_reviews", "fish_oil", "science_based"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Mark Bell",
        "username": "marksmellybell",
        "platform": "instagram",
        "followers": 1100000,
        "engagement_rate": 4.8,
        "avg_views": None,
        "niche": "omega3",
        "content_topics": ["omega3", "powerlifting", "strength", "recovery"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── COLLAGEN & BEAUTY SUPPLEMENTS ───────────────────────────────────────
    {
        "name": "Dr. Josh Axe",
        "username": "drjoshaxe",
        "platform": "instagram",
        "followers": 2300000,
        "engagement_rate": 3.8,
        "avg_views": None,
        "niche": "collagen",
        "content_topics": ["collagen", "gut_health", "essential_oils", "anti_aging", "natural_health"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Dr. Josh Axe",
        "username": "drjoshaxe",
        "platform": "youtube",
        "followers": 1500000,
        "engagement_rate": 4.1,
        "avg_views": 200000,
        "niche": "collagen",
        "content_topics": ["collagen", "natural_medicine", "gut_healing", "herbs"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Melissa Wood",
        "username": "melissawoodhealth",
        "platform": "instagram",
        "followers": 1700000,
        "engagement_rate": 3.5,
        "avg_views": None,
        "niche": "collagen",
        "content_topics": ["collagen", "beauty_supplements", "wellness", "pilates", "mindfulness"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Jojo Gomez",
        "username": "jojogomez",
        "platform": "tiktok",
        "followers": 4500000,
        "engagement_rate": 7.9,
        "avg_views": 1100000,
        "niche": "collagen",
        "content_topics": ["collagen", "beauty", "skin_health", "wellness_routine"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Courtney Swan",
        "username": "realfoodology",
        "platform": "instagram",
        "followers": 510000,
        "engagement_rate": 6.7,
        "avg_views": None,
        "niche": "collagen",
        "content_topics": ["collagen", "clean_beauty", "anti_inflammatory", "real_food"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Caroline Deisler",
        "username": "carolinedeisler",
        "platform": "instagram",
        "followers": 2100000,
        "engagement_rate": 4.4,
        "avg_views": None,
        "niche": "collagen",
        "content_topics": ["collagen", "beauty", "skin_supplements", "anti_aging_routines"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Amanda Bucci",
        "username": "amandabucci",
        "platform": "instagram",
        "followers": 1200000,
        "engagement_rate": 4.9,
        "avg_views": None,
        "niche": "collagen",
        "content_topics": ["collagen", "beauty_wellness", "body_positivity", "clean_beauty"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── WEIGHT MANAGEMENT ────────────────────────────────────────────────────
    {
        "name": "Jordan Syatt",
        "username": "syattfitness",
        "platform": "instagram",
        "followers": 960000,
        "engagement_rate": 6.2,
        "avg_views": None,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "calorie_counting", "fat_loss", "flexible_dieting"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Jordan Syatt",
        "username": "syattfitness",
        "platform": "youtube",
        "followers": 620000,
        "engagement_rate": 6.8,
        "avg_views": 140000,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "fat_loss", "counting_calories", "supplements"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Autumn Calabrese",
        "username": "autumncalabrese",
        "platform": "instagram",
        "followers": 1900000,
        "engagement_rate": 3.6,
        "avg_views": None,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "portion_control", "beachbody", "80_day_obsession"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Dolvett Quince",
        "username": "dolvettquince",
        "platform": "instagram",
        "followers": 890000,
        "engagement_rate": 4.1,
        "avg_views": None,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "motivation", "transformation", "biggest_loser"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Heather Robertson",
        "username": "heatherrobertson",
        "platform": "youtube",
        "followers": 2900000,
        "engagement_rate": 6.3,
        "avg_views": 500000,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "hiit", "fat_burning", "home_workouts"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Gracie Norton",
        "username": "gracienortonfit",
        "platform": "tiktok",
        "followers": 2400000,
        "engagement_rate": 8.4,
        "avg_views": 600000,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "sustainable_dieting", "fat_loss", "healthy_habits"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Victoria Garrick",
        "username": "victoriagarrick",
        "platform": "instagram",
        "followers": 780000,
        "engagement_rate": 5.8,
        "avg_views": None,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "body_image", "intuitive_eating", "mental_health"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Rachel Paul",
        "username": "thecollegenutritionistrd",
        "platform": "instagram",
        "followers": 490000,
        "engagement_rate": 6.9,
        "avg_views": None,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "nutrition_science", "fat_loss", "registered_dietitian"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── GENERAL HEALTH & WELLNESS ────────────────────────────────────────────
    {
        "name": "Andrew Huberman",
        "username": "hubermanlab",
        "platform": "tiktok",
        "followers": 2100000,
        "engagement_rate": 7.2,
        "avg_views": 520000,
        "niche": "general_health",
        "content_topics": ["general_health", "sleep", "stress", "cognitive_performance", "science"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Gary Brecka",
        "username": "garybrecka",
        "platform": "instagram",
        "followers": 3800000,
        "engagement_rate": 7.8,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "biohacking", "human_optimization", "genetics"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Gary Brecka",
        "username": "garybrecka",
        "platform": "tiktok",
        "followers": 5200000,
        "engagement_rate": 9.4,
        "avg_views": 1300000,
        "niche": "general_health",
        "content_topics": ["general_health", "biohacking", "10x_health", "breathwork"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Dave Asprey",
        "username": "daveasprey",
        "platform": "instagram",
        "followers": 950000,
        "engagement_rate": 4.3,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "biohacking", "bulletproof", "nootropics", "longevity"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Ben Greenfield",
        "username": "bengreenfieldfitness",
        "platform": "instagram",
        "followers": 600000,
        "engagement_rate": 5.6,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "biohacking", "ancestral_health", "performance"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Ben Greenfield",
        "username": "bengreenfieldfitness",
        "platform": "youtube",
        "followers": 450000,
        "engagement_rate": 5.9,
        "avg_views": 95000,
        "niche": "general_health",
        "content_topics": ["general_health", "performance", "biohacking", "supplements"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Shawn Stevenson",
        "username": "shawnmodel",
        "platform": "instagram",
        "followers": 420000,
        "engagement_rate": 5.1,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "sleep", "nutrition", "model_health_show"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Kelly LeVeque",
        "username": "bewellbykelly",
        "platform": "instagram",
        "followers": 550000,
        "engagement_rate": 5.7,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "blood_sugar", "fab4_smoothie", "celebrity_nutrition"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "James DiNicolantonio",
        "username": "drjamesdinic",
        "platform": "instagram",
        "followers": 210000,
        "engagement_rate": 7.2,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "salt_health", "electrolytes", "cardiovascular"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },
    {
        "name": "Paul Saladino",
        "username": "carnivoremd",
        "platform": "instagram",
        "followers": 1600000,
        "engagement_rate": 6.4,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "carnivore_diet", "organ_meats", "ancestral_health"],
        "avatar_url": None,
        "email": None,
        "country": "US",
    },

    # ── MIDDLE EAST MARKET ──────────────────────────────────────────────────
    {
        "name": "Omar Isuf",
        "username": "omarisuf",
        "platform": "youtube",
        "followers": 1300000,
        "engagement_rate": 5.8,
        "avg_views": 250000,
        "niche": "protein",
        "content_topics": ["protein", "powerlifting", "bodybuilding", "supplement_reviews"],
        "avatar_url": None,
        "email": None,
        "country": "AE",
    },
    {
        "name": "Fitness Blender",
        "username": "fitnessblender",
        "platform": "youtube",
        "followers": 7200000,
        "engagement_rate": 3.9,
        "avg_views": 800000,
        "niche": "general_health",
        "content_topics": ["general_health", "home_workouts", "cardio", "strength_training"],
        "avatar_url": None,
        "email": None,
        "country": "AE",
    },
    {
        "name": "Ahmed Al Nasser",
        "username": "coach_ahmed_nasser",
        "platform": "instagram",
        "followers": 480000,
        "engagement_rate": 8.9,
        "avg_views": None,
        "niche": "preworkout",
        "content_topics": ["preworkout", "arabic_fitness", "bodybuilding", "muscle_building"],
        "avatar_url": None,
        "email": "coach@ahmed-fitness.ae",
        "country": "AE",
    },
    {
        "name": "Salma Zawawi",
        "username": "salmabyfitness",
        "platform": "instagram",
        "followers": 620000,
        "engagement_rate": 7.4,
        "avg_views": None,
        "niche": "collagen",
        "content_topics": ["collagen", "middle_east_beauty", "wellness", "clean_supplements"],
        "avatar_url": None,
        "email": None,
        "country": "AE",
    },
    {
        "name": "Yousef Al Hammadi",
        "username": "yousefalhammadi_fit",
        "platform": "tiktok",
        "followers": 1800000,
        "engagement_rate": 9.6,
        "avg_views": 480000,
        "niche": "weight_loss",
        "content_topics": ["weight_loss", "arabic_content", "transformation", "supplements"],
        "avatar_url": None,
        "email": None,
        "country": "AE",
    },
    {
        "name": "Farida Hassan",
        "username": "faridfitness",
        "platform": "instagram",
        "followers": 290000,
        "engagement_rate": 8.2,
        "avg_views": None,
        "niche": "vitamins",
        "content_topics": ["vitamins", "arabic_wellness", "womens_health", "nutrition"],
        "avatar_url": None,
        "email": None,
        "country": "AE",
    },
    {
        "name": "Mohamed Khalil",
        "username": "khalilfit_ae",
        "platform": "instagram",
        "followers": 145000,
        "engagement_rate": 9.1,
        "avg_views": None,
        "niche": "probiotics",
        "content_topics": ["probiotics", "gut_health_arabic", "natural_medicine", "wellness"],
        "avatar_url": None,
        "email": "mkhalil@khalilfit.ae",
        "country": "AE",
    },
    {
        "name": "Zara Siddiqui",
        "username": "zarafitlife",
        "platform": "tiktok",
        "followers": 960000,
        "engagement_rate": 8.7,
        "avg_views": 240000,
        "niche": "omega3",
        "content_topics": ["omega3", "south_asian_health", "clean_supplements", "wellness"],
        "avatar_url": None,
        "email": None,
        "country": "AE",
    },
    {
        "name": "Rania Taha",
        "username": "rania_wellness",
        "platform": "instagram",
        "followers": 78000,
        "engagement_rate": 10.3,
        "avg_views": None,
        "niche": "general_health",
        "content_topics": ["general_health", "arabic_wellness", "holistic", "supplements"],
        "avatar_url": None,
        "email": "rania@raniawellness.com",
        "country": "AE",
    },
    {
        "name": "Ali Hassan Fitness",
        "username": "alihassan.fit",
        "platform": "youtube",
        "followers": 380000,
        "engagement_rate": 6.4,
        "avg_views": 85000,
        "niche": "preworkout",
        "content_topics": ["preworkout", "arabic_bodybuilding", "supplement_reviews", "gym_tips"],
        "avatar_url": None,
        "email": None,
        "country": "AE",
    },
]


# ---------------------------------------------------------------------------

def deduplicate_by_username_platform(data: list[dict]) -> list[tuple[str, list[dict]]]:
    """Group platform entries by name so each person becomes one Influencer record."""
    from collections import defaultdict
    groups: dict[str, list[dict]] = defaultdict(list)
    # Use (name) as grouping key to merge multi-platform entries for same person
    for entry in data:
        key = entry["name"].lower().strip()
        groups[key].append(entry)
    return list(groups.items())


def run_seed(dry_run: bool, team_email: str) -> None:
    from app.models.influencer import Influencer, InfluencerPlatform, InfluencerStatus, Platform
    from app.models.user import Team, User

    engine = create_engine(DATABASE_URL, echo=False)

    with Session(engine) as session:
        # Find team
        if team_email:
            user = session.execute(select(User).where(User.email == team_email)).scalar_one_or_none()
            if not user:
                print(f"[ERROR] No user found with email: {team_email}")
                return
            team_id = user.team_id
        else:
            # Use the first team in the DB
            team = session.execute(select(Team).limit(1)).scalar_one_or_none()
            if not team:
                print("[ERROR] No teams found in database. Please register first.")
                return
            team_id = team.id

        print(f"[INFO] Seeding into team_id: {team_id}")

        groups = deduplicate_by_username_platform(INFLUENCER_SEED_DATA)
        created = 0
        skipped = 0

        for name_key, entries in groups:
            first = entries[0]
            name = first["name"]
            niche = first["niche"]
            country = first["country"]
            avatar_url = next((e["avatar_url"] for e in entries if e.get("avatar_url")), None)
            email = next((e["email"] for e in entries if e.get("email")), None)

            # Check duplicate by name + team
            existing = session.execute(
                select(Influencer).where(
                    Influencer.name == name,
                    Influencer.team_id == team_id,
                )
            ).scalar_one_or_none()

            if existing:
                skipped += 1
                print(f"  [SKIP] {name} (already exists)")
                continue

            if dry_run:
                print(f"  [DRY-RUN] Would create: {name} | {niche} | {country} | {len(entries)} platforms")
                for e in entries:
                    print(f"           @{e['username']} on {e['platform']} | {e['followers']:,} followers")
                created += 1
                continue

            influencer = Influencer(
                id=uuid.uuid4(),
                team_id=team_id,
                name=name,
                email=email,
                email_verified=False,
                avatar_url=avatar_url,
                niche=niche,
                country=country,
                status=InfluencerStatus.new,
                source="seeded",
            )
            session.add(influencer)
            session.flush()

            for entry in entries:
                platform_obj = InfluencerPlatform(
                    id=uuid.uuid4(),
                    influencer_id=influencer.id,
                    platform=Platform(entry["platform"]),
                    username=entry["username"],
                    profile_url=f"https://{'tiktok.com/@' if entry['platform'] == 'tiktok' else 'instagram.com/' if entry['platform'] == 'instagram' else 'youtube.com/@'}{entry['username']}",
                    followers=entry.get("followers"),
                    engagement_rate=entry.get("engagement_rate"),
                    avg_views=entry.get("avg_views"),
                    content_topics={"topics": entry.get("content_topics", [])},
                )
                session.add(platform_obj)

            created += 1
            print(f"  [OK] {name} | {niche} | {country}")

        if not dry_run:
            session.commit()

        print(f"\n{'[DRY-RUN] ' if dry_run else ''}Done: {created} created, {skipped} skipped")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed health supplement influencers")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing to DB")
    parser.add_argument("--team-email", default="", help="Email of the user whose team to seed into")
    args = parser.parse_args()
    run_seed(dry_run=args.dry_run, team_email=args.team_email)
