"""add client campaigns and client email messages

Revision ID: 63ad4dbc6fd4
Revises: 136a65e6f5f9
Create Date: 2026-07-09 14:35:45.586426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63ad4dbc6fd4'
down_revision: Union[str, None] = '136a65e6f5f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_campaigns',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'archived', name='clientcampaignstatus'), nullable=False),
    sa.Column('target_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('schedule_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_campaigns_team_id'), 'client_campaigns', ['team_id'], unique=False)
    op.create_table('client_campaign_enrollments',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'in_progress', 'replied', 'completed', 'unsubscribed', 'bounced', name='clientcampaigninfluencerstatus'), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['client_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_campaign_steps',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('delay_days', sa.Integer(), nullable=False),
    sa.Column('condition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['client_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_email_messages',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('campaign_step_id', sa.UUID(), nullable=True),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('email_account_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.Enum('outbound', 'inbound', name='clientemaildirection'), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.Column('in_reply_to', sa.String(length=500), nullable=True),
    sa.Column('references', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'sending', 'sent', 'delivered', 'opened', 'clicked', 'bounced', 'complained', 'failed', name='clientemailstatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['client_campaigns.id'], ),
    sa.ForeignKeyConstraint(['campaign_step_id'], ['client_campaign_steps.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['email_account_id'], ['email_accounts.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email_messages_client_id'), 'client_email_messages', ['client_id'], unique=False)
    op.create_index(op.f('ix_client_email_messages_message_id'), 'client_email_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_client_email_messages_status'), 'client_email_messages', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_email_messages_status'), table_name='client_email_messages')
    op.drop_index(op.f('ix_client_email_messages_message_id'), table_name='client_email_messages')
    op.drop_index(op.f('ix_client_email_messages_client_id'), table_name='client_email_messages')
    op.drop_table('client_email_messages')
    op.drop_table('client_campaign_steps')
    op.drop_table('client_campaign_enrollments')
    op.drop_index(op.f('ix_client_campaigns_team_id'), table_name='client_campaigns')
    op.drop_table('client_campaigns')
    # ### end Alembic commands ###
